import "@/styles/globals.css";
import type { AppProps } from "next/app";
import Head from "next/head";
import { Inter } from "next/font/google";
import { Toaster } from "react-hot-toast";
import { NextComponentType } from "next";
import Sidebar from "@/components/Sidebar";
import Navbar from "@/components/Navbar";
import SessionProvider from "@/contexts/SessionProvider";

const inter = Inter({ subsets: ["latin"] });

interface ExtendedAppProps extends AppProps {
    Component: NextComponentType & { excludeMainLayout?: boolean };
}

export default function App({ Component, pageProps }: ExtendedAppProps) {
    const excludeMainLayout = Component.excludeMainLayout ?? false;

    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={inter.className}>
                <Toaster />
                <SessionProvider>
                    {excludeMainLayout ? (
                        <Component {...pageProps} />
                    ) : (
                        <>
                            <Navbar />
                            <div className={"sidebar"}>
                                <Sidebar />
                                <Component {...pageProps} />
                            </div>
                        </>
                    )}
                </SessionProvider>
            </main>
        </>
    );
}
